# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More

rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/DongbinHu
twitter: https://twitter.com/SixHu
weibo: http://weibo.com/133230866

#about  timeline
timeline:
- num: 1
  word: 2017/06/03-Start
- num: 2
  word: 2017/06/03-XXX
- num: 3
  word: 2017/06/03-DDD
- num: 4
  word: More

#Links
links:
- name: cnblog
  link: http://www.cnblogs.com/-sixgod/
#- name: Name
#  link: http://domain.com/