# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: 为你,千千万万遍...    #YOU'VE MADE A <span>BRAVE</span> DECISION, WELCOME.
- content: #为你，千千万万遍。
bottom_saying: 虽然还没想好写点什么，但是总觉得这里放句话比较和谐。
# Content
excerpt_link: Read More
#rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: SIX
  works_url: /
- works_name: GOD
  works_url: /

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/DongbinHu
twitter: https://twitter.com/SixHu
weibo: http://weibo.com/133230866
bokeyuan: http://www.cnblogs.com/-sixgod/
csdn: http://blog.csdn.net/six__god

#about  timeline
timeline:
- num: 1
  word: 2017/06/03-Start
- num: 2
  word: 2017/06/03-XXX
- num: 3
  word: 2017/06/03-DDD
- num: 4
  word: More

#Links
links:
- name: cnblog
  link: http://www.cnblogs.com/-sixgod/
#- name: Name
#  link: http://domain.com/